export enum ActionType {
    GET_PRODUCTS_IS_PENDING = "GET_PRODUCTS_IS_PENDING",
    GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",

    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",

    CURRENT_PRODUCT_ID="CURRENT_PRODUCT_ID",
    PRODUCT_COUNT="PRODUCT_COUNT",
}